# Generated by Django 5.0.1 on 2024-01-05 18:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_card_created_at_card_image_card_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='card',
            name='count',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
