# Generated by Django 5.0.1 on 2024-01-05 18:42

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0003_card_count'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='card',
            name='count',
        ),
    ]
